// Generated by CoffeeScript 1.7.1
var baseURL, child, currentPanel, panel, setUpButtons, setUpChildPanel, setUpDefinitions, setUpValidation, showNextPanel, showPreviousPanel, submitForm;

panel = 0;

child = 1;

baseURL = 'http://192.168.0.104:8080/';

currentPanel = function() {
  return $('main').children().eq(panel);
};

showPreviousPanel = function() {
  var currPanel, prevPanel;
  currPanel = currentPanel();
  panel--;
  prevPanel = currentPanel();
  $(prevPanel).css("display", "inline-block").animate({
    opacity: 1
  }, 1000);
  $('main').scrollLeft(720).animate({
    scrollLeft: 0
  }, 1000);
  return $(currPanel).animate({
    opacity: 0
  }, 1000, "swing", function() {
    return $(this).css("display", "none");
  });
};

showNextPanel = function() {
  var currPanel, nextPanel;
  currPanel = currentPanel();
  panel++;
  nextPanel = currentPanel();
  $(currPanel).animate({
    opacity: 0
  }, 1000, "swing", function() {
    return $(this).css("display", "none");
  });
  $('main').animate({
    scrollLeft: 720
  }, 1000, "swing", function() {
    return $(this).scrollLeft(0);
  });
  return $(nextPanel).css("display", "inline-block").animate({
    opacity: 1
  }, 1000);
};

submitForm = function() {
  return $.ajax({
    url: baseURL + 'form-submit.json',
    method: 'POST',
    contentType: 'application/json;charset=UTF-8',
    data: '{"text": "Sample PDF", "style":"header"}',
    dataType: 'json'
  }).done(function(data) {
    return console.log(data);
  }).error(function(xhr, error) {
    return console.log('Error Occurred: ' + error);
  });
};

setUpButtons = function() {
  $('#GetStartButton').click(function() {
    return showNextPanel();
  });
  $('.backButton').click(function() {
    return showPreviousPanel();
  });
  $('.nextButton').click(function() {
    return showNextPanel();
  });
  return $('.skipButton').click(function() {
    showNextPanel();
    return showNextPanel();
  });
};

setUpDefinitions = function(parent) {
  parent = parent || 'body';
  $(parent).find('.has-definition').on('focusin mouseenter', function() {
    $('#status-card span').html($(this).attr("data-definition"));
    return $('#status-card').css('display', 'block').animate({
      opacity: 1
    });
  });
  return $(parent).find('.has-definition').on('focusout mouseleave', function() {
    return $('#status-card').animate({
      opacity: 0
    }, 400, "swing", function() {
      return $(this).css('display', 'none');
    });
  });
};

setUpValidation = function(parent) {
  $.validator.addMethod('phoneUS', (function(phone_number, element) {
    phone_number = phone_number.replace(/\s+/g, '');
    return this.optional(element) || phone_number.length > 9 && phone_number.match(/^(1-?)?(\([2-9]\d{2}\)|[2-9]\d{2})-?[2-9]\d{2}-?\d{4}$/);
  }), 'Please enter a valid phone number.');
  $.validator.setDefaults({
    debug: true,
    errorClass: 'invalid',
    validClass: 'valid',
    errorPlacement: function(error, element) {
      return $(element).closest('form').find('label[for=\'' + element.attr('id') + '\']').attr('data-error', error.text());
    },
    submitHandler: function(form) {
      return console.log('form ok');
    },
    rules: {
      parentFirstName: 'required',
      parentLastName: 'required',
      email: 'email',
      phone: 'phoneUS',
      zip: 'digits',
      childFirstName: 'required',
      childLastName: 'required'
    }
  });
  return $('form').each(function() {
    return $(this).validate({});
  });
};

setUpChildPanel = function() {
  var addChild, template, templateHTML;
  template = $('#child-num-Form');
  templateHTML = $(template)[0].outerHTML;
  $(template).remove();
  addChild = function() {
    var newElement, newHTML;
    newHTML = templateHTML.replace(/-num-/g, child.toString());
    newElement = $.parseHTML(newHTML);
    setUpDefinitions(newElement);
    $(newElement).validate({});
    $('#addChildSection').before(newElement);
    $('#child' + child + 'FirstName').on('change keyup input', function() {
      var val;
      val = $(this).val();
      if (val) {
        return $(this).closest('form').find('h5').html($(this).val());
      } else {
        return $(this).closest('form').find('h5').html('New Child');
      }
    });
    child++;
    return $(newElement).find('.removeChild').click(function() {
      if ($('.childForm').size() === 1) {
        return Materialize.toast('You must have at least one child.', 4000);
      } else {
        return $(this).closest('form').remove();
      }
    });
  };
  $('#addChild').click(function() {
    return addChild();
  });
  return addChild();
};

$(function() {
  setUpButtons();
  setUpDefinitions();
  setUpValidation();
  setUpChildPanel();
  return $('select').material_select();
});
