// Generated by CoffeeScript 1.7.1
var data3;

data3 = {
  'parent': {
    'parentFirstName': 'Jatin',
    'parentLastName': 'Frost',
    'email': 'jat-frost@geocities.com',
    'phone': '669-221-6251',
    'address': '6087 Pleasant Forest Line',
    'city': 'Tin City',
    'state': 'NH',
    'zipCode': '03672'
  },
  'children': [
    {
      'FirstName': 'Arland',
      'MiddleName': null,
      'LastName': 'Frost',
      'student': true,
      'foster': true,
      'homeless': false,
      'migrant': false,
      'runaway': false
    }
  ],
  'adults': null,
  'program': null,
  'earner': null,
  'agreement': null
};
